

[server]
# Allow WebSocket compression to reduce data transfer
server.enableWebsocketCompression = true

[client]
# Reduce bandwidth usage
caching = "true"
displayEnabled = "true"

[runner]
# Disable script reruns for every interaction
magicEnabled = false