[theme]
base = "dark"  
primaryColor = "#1d70b8"  
backgroundColor = "#121212"  
secondaryBackgroundColor = "#1e1e1e"  
textColor = "#e0e0e0"  
font = "sans-serif"  


[server]
# Allow WebSocket compression to reduce data transfer
server.enableWebsocketCompression = true

[client]
# Reduce bandwidth usage
caching = "true"
displayEnabled = "true"

[runner]
# Disable script reruns for every interaction
magicEnabled = false